route:
  receiver: "email-alert"

receivers:
  - name: "email-alert"
    email_configs:
      - to: "jonathanta2023@gmail.com"
        from: "alertmanager@example.com"
        smarthost: "smtp.gmail.com:587"
        auth_username: "your-email@example.com"
        auth_password: "your-password"
